[server]
# Desactiva la corona de Streamlit (marca de agua)
enableCORS = false

[theme]
# Activa el tema oscuro
base="dark"
primaryColor="#007BFF"
backgroundColor="#000000"
secondaryBackgroundColor="#2F2F2F"
textColor="#FAFAFA"
font="sans serif"
